# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('access_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
